// BOM (Bill of Materials) export — CSV and XLSX.
import { SchematicDoc } from "./schematic";
import { SYMBOLS } from "./symbols";

export interface BomRow {
  reference: string;
  value: string;
  symbol: string;
  category: string;
  pins: number;
  quantity: number;
}

export function buildBom(doc: SchematicDoc): BomRow[] {
  // Group by symbol + value
  const map = new Map<string, BomRow & { refs: string[] }>();
  for (const n of doc.nodes) {
    const sym = SYMBOLS[n.symbol];
    if (!sym) continue;
    const key = `${n.symbol}::${n.value ?? ""}`;
    const ref = n.reference ?? "—";
    const cur = map.get(key);
    if (cur) {
      cur.refs.push(ref);
      cur.quantity++;
    } else {
      map.set(key, {
        reference: "",
        value: n.value ?? "",
        symbol: n.symbol,
        category: sym.category,
        pins: sym.pins.length,
        quantity: 1,
        refs: [ref],
      });
    }
  }
  const rows: BomRow[] = [];
  for (const r of map.values()) {
    rows.push({ ...r, reference: r.refs.sort().join(", ") });
  }
  rows.sort((a, b) => a.symbol.localeCompare(b.symbol));
  return rows;
}

export function buildNetlist(doc: SchematicDoc): string {
  // Simple connectivity netlist: each wire becomes a net; pins joined via shared wire endpoints.
  // Output format: NET <id> : RefA.pin1 RefB.pin2 ...
  // (Best-effort — uses point-coincidence between wire endpoints and pin positions.)
  const eps = 0.05;
  // Build pin lookup: list of { ref, pin#, x, y }
  type PinKey = { ref: string; pin: number; x: number; y: number };
  const pinList: PinKey[] = [];
  for (const n of doc.nodes) {
    const sym = SYMBOLS[n.symbol];
    if (!sym) continue;
    sym.pins.forEach((p, i) => {
      // rotated position
      const cx = sym.width / 2, cy = sym.height / 2;
      const rad = (n.rotation * Math.PI) / 180;
      const cos = Math.cos(rad), sin = Math.sin(rad);
      const px = cx + (p.x - cx) * cos - (p.y - cy) * sin;
      const py = cy + (p.x - cx) * sin + (p.y - cy) * cos;
      pinList.push({ ref: n.reference ?? n.symbol, pin: i + 1, x: n.x + px, y: n.y + py });
    });
  }
  // Union-find on wire connectivity (each wire is one net)
  const lines: string[] = ["# Netlist generated by CirZuit"];
  doc.wires.forEach((w, i) => {
    const connected: string[] = [];
    for (const p of w.points) {
      for (const pk of pinList) {
        if (Math.hypot(p.x - pk.x, p.y - pk.y) < eps) {
          const tag = `${pk.ref}.${pk.pin}`;
          if (!connected.includes(tag)) connected.push(tag);
        }
      }
    }
    lines.push(`NET${i + 1} : ${connected.join(" ")}`);
  });
  return lines.join("\n");
}

export function downloadBomCsv(doc: SchematicDoc, filename: string) {
  const rows = buildBom(doc);
  const csvContent = "data:text/csv;charset=utf-8," 
    + ["Reference,Value,Symbol,Category,Pins,Quantity"].join(",") + "\n"
    + rows.map(r => `"${r.reference}","${r.value}","${r.symbol}","${r.category}",${r.pins},${r.quantity}`).join("\n");
  const encodedUri = encodeURI(csvContent);
  const a = document.createElement("a");
  a.setAttribute("href", encodedUri);
  a.setAttribute("download", `${filename}-bom.csv`);
  document.body.appendChild(a);
  a.click();
  a.remove();
}

export async function downloadBomXlsx(doc: SchematicDoc, filename: string) {
  const XLSX = await import("xlsx");
  const rows = buildBom(doc);
  const data = [
    ["Reference", "Value", "Symbol", "Category", "Pins", "Qty"],
    ...rows.map((r) => [r.reference, r.value, r.symbol, r.category, r.pins, r.quantity]),
  ];
  const ws = XLSX.utils.aoa_to_sheet(data);
  ws["!cols"] = [{ wch: 20 }, { wch: 14 }, { wch: 14 }, { wch: 12 }, { wch: 6 }, { wch: 6 }];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "BOM");
  // Netlist sheet
  const net = buildNetlist(doc).split("\n").map((l) => [l]);
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(net), "Netlist");
  XLSX.writeFile(wb, `${filename}-bom.xlsx`);
}

export function downloadNetlist(doc: SchematicDoc, filename: string) {
  const content = buildNetlist(doc);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `${filename}.net`;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
}
